run:
  skip-dirs-use-defaults: true
linters:
  disable-all: true
  enable:
    - gofmt
    - golint
    - goimports
    - govet
    - deadcode
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - goconst
    - unconvert
