name: Clutter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Shellcheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -e SC2059
    - name: Build
      run: make clutter
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.35.2
    - name: Unit Tests
      run: make test-unit
    - name: End-to-End Tests
      run: make test-end-to-end
